apiVersion: v1
kind: Service
metadata:
  name: websockets
  labels:
    app: websockets
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: websockets
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: websockets-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: websockets
        version: v1
    spec:
      containers:
      - image: gcr.io/nandanks-151422/websockets
        imagePullPolicy: IfNotPresent
        name: websockets
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
  namespace: default
spec:
  gateways:
  - helloworld-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        exact: /hello
    route:
    - destination:
        host: helloworld
        port:
          number: 5000
  - match:
    - uri:
        exact: /v1/ws
    route:
    - destination:
        host: websockets
        port:
          number: 3000
    websocketUpgrade: true
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: websockets
        port:
          number: 3000